spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shareyourrecipe?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080

app:
  jwt:
    secret: "i_am_batman"
    expirationMs: 604800000 # 7 days


